Search Applicants by Notes
AY2324S2-CS2103-F15-3/tp pull request #89
Opened 2024-03-27 16:05 UTC by YuvBindal

2024-03-27 16:15 UTC, YuvBindal reviewed
Need to fix checkstyle issues

2024-03-27 16:16 UTC, YuvBindal reviewed
Should be good to merge other wise?

2024-03-27 16:16 UTC, YuvBindal reviewed
LGTM

2024-03-28 09:18 UTC, ys112 requested changes
Would like to bring your attention to a couple of things to take note of:
1. I tried running the app and it would not show 2 applicants with the same keyword.
2. Highly suggest fixing the check style issues first before merging as the CI is crucial to ensure our app can be built and catch any issues in the earlier stage.
3. Seems like your code is not up to date from the latest master commit from the team's tp as I noticed the notes feature is still before the fix.

Steps to replicate issue:
1. Have 2 applicants with "forbes" in notes
4. search /notes forbes
5. List empty

2024-03-28 09:18 UTC, ys112 commented on src/main/java/seedu/address/logic/commands/SearchApplicantCommand.java
> +            // Check if the roleName matches filteredRole and stageName matches filteredStage
Comment does not seem to match context here too.

2024-04-03 11:17 UTC, closed without merging